  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: "/home/pi/dev/mjolnir-hamma/files/status_bot.py -m 'wut'": "/home/pi/dev/mjolnir-hamma/files/status_bot.py -m 'wut'" (T+1908 ms)
2020-05-29 21:02:28.032 | INFO | Telemetry Process | plugins.state_monitor.StateNotifier | Current data: {'time': '2020-05-29 21:02:27.596547+00:00', 'runtime': '1.432', 'adc_vb_f': '13.544', 'adc_va_f': '18.781', 'adc_vl_f': '13.461', 'adc_ic_f': '2.773', 'adc_il_f': '1.708', 't_hs': '50', 't_batt': '50', 't_amb': '50', 't_rts': '25', 'charge_state': '6', 'array_fault': '0', 'vb_f': '13.544', 'vb_ref': '13.086', 'ahc_r': '603.7', 'ahc_t': '603.7', 'kwhc': '7.7', 'load_state': '1', 'load_fault': '0', 'v_lvd': '11.499', 'ahl_r': '595.5', 'ahl_t': '595.5', 'hourmeter': '3686', 'alarm': '1', 'dip_switch': '13', 'led_state': '5', 'power_out': '37.173', 'sweep_vmp': '14.917', 'sweep_pmax': '34.697', 'sweep_voc': '18.39', 'vb_min_daily': '11.288', 'vb_max_daily': '13.983', 'ahc_daily': '31.9', 'ahl_daily': '18.2', 'array_fault_daily': '0', 'load_fault_daily': '0', 'alarm_daily': '1', 'vb_min': '10.779', 'vb_max': '20.898', 'ping': '0', 'sequence_count': '190', 'timestamp': '2018-01-16 11:23:24.812000+00:00', 'crc_errors': '0', 'valid_packets': '0', 'bytes_read': '0.025427968', 'bytes_written': '0.0', 'bytes_remaining': '320.519131136', 'packets_sent': '0', 'packets_dropped': '0'} (T+1915 ms)
2020-05-29 21:02:28.033 | INFO | Telemetry Process | plugins.state_monitor.StateNotifier | Previous data: {'time': '2020-05-29 21:02:27.596547+00:00', 'runtime': '1.432', 'adc_vb_f': '13.544', 'adc_va_f': '18.781', 'adc_vl_f': '13.461', 'adc_ic_f': '2.773', 'adc_il_f': '1.708', 't_hs': '50', 't_batt': '50', 't_amb': '50', 't_rts': '25', 'charge_state': '6', 'array_fault': '0', 'vb_f': '13.544', 'vb_ref': '13.086', 'ahc_r': '603.7', 'ahc_t': '603.7', 'kwhc': '7.7', 'load_state': '1', 'load_fault': '0', 'v_lvd': '11.499', 'ahl_r': '595.5', 'ahl_t': '595.5', 'hourmeter': '3686', 'alarm': '1', 'dip_switch': '13', 'led_state': '5', 'power_out': '37.173', 'sweep_vmp': '14.917', 'sweep_pmax': '34.697', 'sweep_voc': '18.39', 'vb_min_daily': '11.288', 'vb_max_daily': '13.983', 'ahc_daily': '31.9', 'ahl_daily': '18.2', 'array_fault_daily': '0', 'load_fault_daily': '0', 'alarm_daily': '1', 'vb_min': '10.779', 'vb_max': '20.898', 'ping': '0', 'sequence_count': '190', 'timestamp': '2018-01-16 11:23:24.812000+00:00', 'crc_errors': '0', 'valid_packets': '0', 'bytes_read': '0.025427968', 'bytes_written': '0.0', 'bytes_remaining': '320.519131136', 'packets_sent': '0', 'packets_dropped': '0'} (T+1916 ms)
2020-05-29 21:02:29.253 | WARNING | MainProcess | brokkr.multiprocess.handler | Interrupted by signal 2; terminating. (T+3137 ms)
2020-05-29 21:02:29.253 | WARNING | Telemetry Process | brokkr.pipeline.pipeline.SequentialPipeline | Interrupted by signal 2; terminating. (T+3136 ms)
2020-05-29 21:02:29.393 | INFO | MainProcess | brokkr.multiprocess.handler | Exiting manager (T+3277 ms)
2020-05-29 21:02:29.393 | INFO | MainProcess | brokkr.multiprocess.handler | Beginning worker shutdown (T+3277 ms)
2020-05-29 21:02:29.394 | INFO | MainProcess | brokkr.multiprocess.handler | Attempting to shut down worker <Process(Telemetry Process, started)> (T+3277 ms)
2020-05-29 21:02:29.535 | INFO | Telemetry Process | brokkr.pipeline.pipeline.SequentialPipeline | Shutting down Telemetry (brokkr.pipeline.pipeline.SequentialPipeline) (T+3419 ms)
2020-05-29 21:02:30.022 | ERROR | Telemetry Process | plugins.state_monitor.StateNotifier | FileNotFoundError evaluating in <class 'plugins.state_monitor.StateNotifier'> on step HW: [Errno 2] No such file or directory: "/home/pi/dev/mjolnir-hamma/files/status_bot.py -m 'wut'": "/home/pi/dev/mjolnir-hamma/files/status_bot.py -m 'wut'" (T+3906 ms)
2020-05-29 21:02:30.024 | INFO | Telemetry Process | plugins.state_monitor.StateNotifier | Error details:
Traceback (most recent call last):
  File "/home/pi/dev/mjolnir-hamma/plugins/state_monitor.py", line 89, in execute
    subprocess.call(SCRIPT + " -m 'wut'")
  File "/usr/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: "/home/pi/dev/mjolnir-hamma/files/status_bot.py -m 'wut'": "/home/pi/dev/mjolnir-hamma/files/status_bot.py -m 'wut'" (T+3908 ms)
2020-05-29 21:02:30.027 | INFO | Telemetry Process | plugins.state_monitor.StateNotifier | Current data: {'time': '2020-05-29 21:02:29.536136+00:00', 'runtime': '3.371', 'adc_vb_f': '13.541', 'adc_va_f': '18.781', 'adc_vl_f': '13.461', 'adc_ic_f': '2.742', 'adc_il_f': '1.681', 't_hs': '50', 't_batt': '50', 't_amb': '50', 't_rts': '25', 'charge_state': '6', 'array_fault': '0', 'vb_f': '13.541', 'vb_ref': '13.086', 'ahc_r': '603.7', 'ahc_t': '603.7', 'kwhc': '7.7', 'load_state': '1', 'load_fault': '0', 'v_lvd': '11.499', 'ahl_r': '595.5', 'ahl_t': '595.5', 'hourmeter': '3686', 'alarm': '1', 'dip_switch': '13', 'led_state': '5', 'power_out': '37.218', 'sweep_vmp': '14.917', 'sweep_pmax': '34.697', 'sweep_voc': '18.39', 'vb_min_daily': '11.288', 'vb_max_daily': '13.983', 'ahc_daily': '31.9', 'ahl_daily': '18.2', 'array_fault_daily': '0', 'load_fault_daily': '0', 'alarm_daily': '1', 'vb_min': '10.779', 'vb_max': '20.898', 'ping': '0', 'sequence_count': '192', 'timestamp': '2018-01-16 11:23:26.813000+00:00', 'crc_errors': '0', 'valid_packets': '0', 'bytes_read': '0.025690112', 'bytes_written': '0.0', 'bytes_remaining': '320.519131136', 'packets_sent': '0', 'packets_dropped': '0'} (T+3911 ms)
2020-05-29 21:02:30.028 | INFO | Telemetry Process | plugins.state_monitor.StateNotifier | Previous data: {'time': '2020-05-29 21:02:27.596547+00:00', 'runtime': '1.432', 'adc_vb_f': '13.544', 'adc_va_f': '18.781', 'adc_vl_f': '13.461', 'adc_ic_f': '2.773', 'adc_il_f': '1.708', 't_hs': '50', 't_batt': '50', 't_amb': '50', 't_rts': '25', 'charge_state': '6', 'array_fault': '0', 'vb_f': '13.544', 'vb_ref': '13.086', 'ahc_r': '603.7', 'ahc_t': '603.7', 'kwhc': '7.7', 'load_state': '1', 'load_fault': '0', 'v_lvd': '11.499', 'ahl_r': '595.5', 'ahl_t': '595.5', 'hourmeter': '3686', 'alarm': '1', 'dip_switch': '13', 'led_state': '5', 'power_out': '37.173', 'sweep_vmp': '14.917', 'sweep_pmax': '34.697', 'sweep_voc': '18.39', 'vb_min_daily': '11.288', 'vb_max_daily': '13.983', 'ahc_daily': '31.9', 'ahl_daily': '18.2', 'array_fault_daily': '0', 'load_fault_daily': '0', 'alarm_daily': '1', 'vb_min': '10.779', 'vb_max': '20.898', 'ping': '0', 'sequence_count': '190', 'timestamp': '2018-01-16 11:23:24.812000+00:00', 'crc_errors': '0', 'valid_packets': '0', 'bytes_read': '0.025427968', 'bytes_written': '0.0', 'bytes_remaining': '320.519131136', 'packets_sent': '0', 'packets_dropped': '0'} (T+3911 ms)
2020-05-29 21:02:30.038 | INFO | MainProcess | brokkr.multiprocess.handler | Process <Process(Telemetry Process, stopped)> shut down (T+3922 ms)
2020-05-29 21:02:30.039 | INFO | MainProcess | brokkr.multiprocess.handler | Worker shutdown finished in 645.1 ms with 0 terminated, 0 failed (T+3922 ms)
2020-05-29 21:02:30.039 | INFO | MainProcess | brokkr.multiprocess.handler | Shutting down logging process (T+3923 ms)
2020-05-29 21:02:30.047 | INFO | LogProcess | brokkr.multiprocess.loglistener | Shutting down logging system (T+3930 ms)
2020-05-29 21:02:30.048 | INFO | LogProcess | brokkr.multiprocess.loglistener | Logging system shut down (T+3931 ms)
