2020-05-11 15:00:52.714 | INFO | MainProcess | brokkr.start | Presets config: ['builtins', 'hamma2', 'sunsaver_mppt_15l'] (T+1846 ms)
2020-05-11 15:00:52.715 | INFO | MainProcess | brokkr.multiprocess.handler | Starting worker process <Process(Telemetry Process, initial)> (T+1846 ms)
2020-05-11 15:00:52.721 | INFO | MainProcess | brokkr.multiprocess.handler | Finished starting worker process <Process(Telemetry Process, started)> (T+1852 ms)
2020-05-11 15:00:52.723 | INFO | MainProcess | brokkr.multiprocess.handler | Starting manager (T+1855 ms)
2020-05-11 15:00:52.729 | INFO | Telemetry Process | brokkr.multiprocess.handler | Started worker process Telemetry Process (T+1861 ms)
2020-05-11 15:00:52.947 | INFO | Telemetry Process | brokkr.pipeline.pipeline.SequentialPipeline | Beginning execution of Telemetry (brokkr.pipeline.pipeline.SequentialPipeline) (T+2079 ms)
2020-05-11 15:00:54.971 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | ModbusIOException reading Modbus data for None: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received) (T+4103 ms)
2020-05-11 15:00:54.971 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error details:
Traceback (most recent call last):
  File "/home/pi/dev/brokkr/src/brokkr/inputs/modbus.py", line 89, in _get_responce_data
    raise responce_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received) (T+4103 ms)
2020-05-11 15:00:54.974 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb5565930>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb5565770>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyUSB0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': 1589209254.968013, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401, 'state': 6} (T+4105 ms)
2020-05-11 15:00:54.974 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: None (T+4106 ms)
2020-05-11 15:01:02.958 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | ModbusIOException reading Modbus data for None: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received) (T+12090 ms)
2020-05-11 15:01:02.959 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error details:
Traceback (most recent call last):
  File "/home/pi/dev/brokkr/src/brokkr/inputs/modbus.py", line 89, in _get_responce_data
    raise responce_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received) (T+12090 ms)
2020-05-11 15:01:02.959 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb55701d0>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb5570810>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyUSB0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': 1589209262.953929, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401, 'state': 6} (T+12091 ms)
2020-05-11 15:01:02.959 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: None (T+12091 ms)
2020-05-11 15:01:12.961 | ERROR | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | ModbusIOException reading Modbus data for None: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received) (T+22093 ms)
2020-05-11 15:01:12.962 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Error details:
Traceback (most recent call last):
  File "/home/pi/dev/brokkr/src/brokkr/inputs/modbus.py", line 89, in _get_responce_data
    raise responce_data
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] Incomplete message received, expected at least 2 bytes (0 received) (T+22093 ms)
2020-05-11 15:01:12.963 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Client details: {'method': 'rtu', 'socket': None, 'framer': <pymodbus.framer.rtu_framer.ModbusRtuFramer object at 0xb5570a50>, 'transaction': <pymodbus.transaction.DictTransactionManager object at 0xb5570190>, '_debug': False, '_debugfd': None, 'broadcast_enable': False, 'port': '/dev/ttyUSB0', 'stopbits': 2, 'bytesize': 8, 'parity': 'N', 'baudrate': 9600, 'timeout': 2, '_strict': False, 'last_frame_end': 1589209272.957435, '_t0': 0.0011458333333333333, 'inter_char_timeout': 0.00171875, 'silent_interval': 0.00401, 'state': 6} (T+22094 ms)
2020-05-11 15:01:12.963 | INFO | Telemetry Process | brokkr.inputs.modbus.ModbusSerialInput | Port details: None (T+22095 ms)
